routes/web.php
    Route::get('modelsdetails/{id}', 'Admin\BrandModelController@modelsDetails')->name('models.modelsDetails');

    Route::get('get-brand-type-list', 'Admin\BrandModelController@getBrandTypes');
    Route::get('get-model-list', 'Admin\BrandModelController@getModelList');

    /*** Brand Submodel NT **/
    Route::resource('submodels', 'Admin\BrandSubModelController');
    Route::post('submodels-order-position', 'Admin\BrandSubModelController@submodelsOrderPosition')->name('submodelsOrderPosition');
    Route::get('changeSubmodelStatus', 'Admin\BrandSubModelController@changeStatus');
    Route::get('deleteSubModel/{id}', 'Admin\BrandSubModelController@deleteSubModel');
    Route::delete('submodels_mass_destroy', 'Admin\BrandSubModelController@massDestroy')->name('submodels.mass_destroy');
    Route::get('submodelDetails/{id}', 'Admin\BrandSubModelController@submodelDetails')->name('submodels.submodelDetails');

    Route::get('get-sub-brand-type-list', 'Admin\BrandSubModelController@getBrandTypes');

    /*** BrandModelScreenImageController **/
    Route::resource('models-screen-image', 'Admin\BrandModelScreenImageController');
    Route::post('models-screen-image-order-position', 'Admin\BrandModelScreenImageController@modelsScreenImageOrderPosition')->name('modelsScreenImageOrderPosition');
    Route::get('changeStatusModelScreen', 'Admin\BrandModelScreenImageController@changeStatusModelScreen');
    //Route::get('deleteModelScreenBltFiles', 'Admin\BrandModelScreenImageController@deleteModelScreenBltFiles');
    Route::get('deleteModelScreenImage', 'Admin\BrandModelScreenImageController@deleteModelScreenImage');
    Route::get('deleteModelScreenBltFiles/{id}', 'Admin\BrandModelScreenImageController@deleteModelScreenBltFiles');
    Route::delete('models_screen_image_mass_destroy', 'Admin\BrandModelScreenImageController@massDestroy')->name('models-screen-image.mass_destroy');
    Route::get('models-screen-image-list', 'Admin\BrandModelScreenImageController@modelScreenImageDetails')->name('models-screen-image-list');
    Route::get('deleteModelScreen/{id}', 'Admin\BrandModelScreenImageController@deleteModelScreen');


    Route::get('get-brand-list', 'Admin\BrandModelScreenImageController@getBrand');
    Route::post('addMoreImage', 'Admin\BrandModelScreenImageController@addMoreImage');

    /*** Bulk Upload NT **/
    Route::get('bulkupload', 'Admin\BulkUploadController@create')->name('bulkupload.create');
    Route::post('bulkupload/store', 'Admin\BulkUploadController@store')->name('bulkupload.store');
    Route::post('bulk-export', 'Admin\BulkUploadController@export')->name('bulkupload.export');

    /*** Retailers **/
    Route::resource('retailers', 'Admin\RetailerController');
    Route::post('retailers-list-deleteall', 'Admin\RetailerController@retailerDeleteAll');

    /*** Plans NT **/
    Route::resource('plans', 'Admin\PlanController');
    Route::get('changeStatusPlan', 'Admin\PlanController@changeStatus');
    Route::get('plan/delete/{id}', 'Admin\PlanController@deletePlan');
    Route::delete('plans_mass_destroy', 'Admin\PlanController@massDestroy')->name('plans.mass_destroy');
    Route::post('upload/serialnumber/{id}', 'Admin\PlanController@uploadSerialNumbers')->name('plans.upload.serialnumber');


    Route::resource('serial-numbers', 'Admin\SerialNumbersController');

    Route::resource('machine-numbers', 'Admin\MachineNumbersController');
    Route::post('upload/machinenumber', 'Admin\MachineNumbersController@uploadMachineNumbers')->name('upload.machinenumber');

    /*** Indivisual user commission change  NT **/
    Route::post('plan/change/{id}', 'Admin\RetailerController@changeCurrentPlan')->name('planChangeAdmin');

    /*customer Recharge Commission NT26022121*/
    Route::get('customer-recharge-commission', 'Admin\RetailerController@customerRechargeCommission')->name('customer-recharge-commission');
    Route::get('customer-recharge-commission-report', 'Admin\RetailerController@customerRechargeCommissionReport')->name('customer-recharge-commission-report');

    /*customer profile change NT26022121*/
    Route::get('retailer-profile-change-request', 'Admin\RetailerController@retailerProfileChangeRequestList')->name('retailer-profile-change-request');
    Route::get('change-profile-request-status', 'Admin\RetailerController@changeProfileRequestStatus');

    /*customer imei change request list and update NT26022121*/
    Route::get('imei-change-request-list', 'Admin\RetailerController@imeiChangeRequestList')->name('imei-change-request');
    Route::get('update-imei-request/{id}', 'Admin\RetailerController@updateImeiRequest');

    /*Currency show and update NT04032121*/
    Route::get('setting/currency', 'Admin\SettingController@currencySetting')->name('setting.currency');
    Route::get('setting/website', 'Admin\SettingController@websiteSetting')->name('setting.website');
    Route::get('setting/otpprice', 'Admin\SettingController@otppriceSetting')->name('setting.otpprice');
    Route::put('setting/otpprice-update', 'Admin\SettingController@otppriceUpdate')->name('setting.otpprice-update');
    Route::put('setting/currency-update', 'Admin\SettingController@updateCurrencySetting')->name('setting.currency-update');

    Route::post('addShopGallery', 'Admin\RetailerController@addShopGallery');
    Route::get('deleteShopGallery', 'Admin\RetailerController@deleteShopGallery');
    Route::get('get-state-list', 'Admin\UsersController@getStateList');
    Route::get('kyc/changeStatus', 'Admin\RetailerController@approveKyc');
    Route::post('kyc/adminChangeStatus', 'Admin\RetailerController@approveKycAdmin');

    Route::resource('recharge-plan', 'Admin\RechargePlanController');
    Route::get('recharge-plan/delete/{id}', 'Admin\RechargePlanController@deleteRechargePlan');
    Route::get('changeStatusRechargePlan', 'Admin\RechargePlanController@changeStatus');
    Route::resource('video', 'Admin\VideoController');
    Route::post('video-order-position', 'Admin\VideoController@videoOrderPosition')->name('videoOrderPosition');
    Route::get('video/delete/{id}', 'Admin\VideoController@deleteVideo');

    Route::resource('video-category', 'Admin\VideoCategoryController');
    Route::post('video-category-order-position', 'Admin\VideoCategoryController@videoCategoryOrderPosition')->name('videoCategoryOrderPosition');
    Route::get('video-category/delete/{id}', 'Admin\VideoCategoryController@deleteVideoCategory');
    Route::get('changeStatusVideoCategory', 'Admin\VideoCategoryController@changeStatus');

    /*PaperSizeController NT09031644*/
    /*Route::resource('/paper-size', 'Admin\PaperSizeController');
    Route::get('/paper-size/delete/{id}', 'Admin\PaperSizeController@deletePaperSize');
    Route::get('/changeStatusPaperSize/', 'Admin\PaperSizeController@changeStatus');
    */

    Route::resource('paper-sizes', 'Admin\PaperSizeController');
    /* ---------create by neha---------*/
    // Route::get('privacypolicy', 'Admin\SettingController@privacypolicy')->name('privacypolicy');

    Route::any('setting/privacypolicy', 'Admin\SettingController@privacypolicy')->name('setting.privacypolicy');
    Route::any('setting/setting_pdf', 'Admin\SettingController@settingpdf')->name('setting.setting_pdf');
    Route::post('setting/settingpdf-update', 'Admin\SettingController@updateSettingPdf')->name('setting.settingpdf-update');
    Route::post('setting/settingpdf-order', 'Admin\SettingController@updateSettingPdfOrder')->name('setting.settingpdf-order');
    Route::post('setting/settingpdf-delete', 'Admin\SettingController@updateSettingPdfDelete')->name('setting.settingpdf-delete');

    Route::put('setting/privacypolicy-update', 'Admin\SettingController@updatePrivacypolicy')->name('setting.privacypolicy-update');
    Route::post('setting/listprivacypolicy', 'Admin\SettingController@listprivacypolicy')->name('setting.listprivacypolicy');


    /* Route::get('customer-recharge-commission', 'Admin\RetailerController@customerRechargeCommission')->name('customer-recharge-commission');*/


    Route::put('fix-commission-update', 'Admin\RetailerController@fixcommissionupdate')->name('fixcommissionupdate');
    Route::put('fix-reward-update', 'Admin\RetailerController@fixrewardupdate')->name('fixrewardupdate');

    Route::get('paper-sizes/delete/{paperSize}', 'Admin\PaperSizeController@deletePaperSize')->name('paper-sizes.delete');
    Route::get('/changeStatusPaperSize/', 'Admin\PaperSizeController@changeStatus');


    Route::resource('generalnotification', 'Admin\GeneralNotificationController');
    Route::post('generalnotification/save', 'Admin\GeneralNotificationController@savenotification')->name('savenotification');
    Route::post('generalnotification/delete/{id}', 'Admin\GeneralNotificationController@delete')->name('deletenotification');
    Route::resource('banner', 'Admin\BannerController');
    Route::post('banner-order-position', 'Admin\BannerController@bannerOrderPosition')->name('bannerOrderPosition');
    Route::get('createBanner/{id}', 'Admin\BannerController@create')->name('createBanner');
    Route::get('bannerdetails/{id}', 'Admin\BannerController@bannerDetails')->name('bannerDetails');
    Route::get('banner/delete/{id}', 'Admin\BannerController@delete');
    Route::get('changeStatusBanner', 'Admin\BannerController@changeStatus');

    Route::resource('bulkcut-plan', 'Admin\BulkCutPlanController');
    Route::get('bulkcut/delete/{id}', 'Admin\BulkCutPlanController@deleteBulkCutPlan');
    Route::get('changeStatusBulkCutPlan', 'Admin\BulkCutPlanController@changeStatus');
    //Divya Route


    /*Member Tree*/
    Route::get('member-tree', 'Admin\RetailerController@showMemberTree')->name('members-tree');
    Route::get('tree-view-retailers/{id}', 'Admin\RetailerController@showMemberTreeDetail')->name('tree-view-retailers');


    Route::get('setting/credit-point', 'Admin\SettingController@creditPoint')->name('setting.credit-point');

app/Models/MachineNumbers.php
<?php



namespace App\Models;



use App\User;

use Illuminate\Database\Eloquent\Model;

use Illuminate\Database\Eloquent\SoftDeletes;



class MachineNumbers extends Model {



    protected $table = 'machine_numbers';

    protected $fillable = ['machine_number','customer_name','quantity','plan','status'];



}

app/Http/Controllers/Admin/MachineNumbersController.php
<?php



namespace App\Http\Controllers\Admin;



use Spatie\Permission\Models\Permission;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

use App\Models\Plan;

use App\Models\PlanCommission;

use App\Models\CommissionSetting;

use App\Models\BrandType;

use App\Models\PlanBrandTypes;

use App\Models\PlanSerialNumbers;

use App\Models\MachineNumbers;

use Illuminate\Support\Facades\Gate;

use Illuminate\Support\Str;

Use Alert;

use File;

use DB;



class MachineNumbersController extends Controller {



    public function index() {

        return redirect()->action('Admin\MachineNumbersController@machineNumberDetails');

        $machineNumbers = MachineNumbers::select('machine_numbers.*','users.name as username','users.id as u_id')
            ->leftJoin('user_kyc_details as ky', 'ky.machine_number', '=', 'machine_numbers.machine_number')
            ->leftJoin('users', 'users.id', '=', 'ky.user_id')
            ->orderBy('id', 'DESC')->get();

        return view('admin.machine-numbers.index', compact('machineNumbers'));
    }

    public function machineNumberDetails(Request $request) {
        $machineNumbers = MachineNumbers::select('machine_numbers.*','users.name as username','users.id as u_id')
            ->leftJoin('user_kyc_details as ky', 'ky.machine_number', '=', 'machine_numbers.machine_number')
            ->leftJoin('users', 'users.id', '=', 'ky.user_id')
            ->orderBy('id', 'DESC')->get();
        return view('admin.machine-numbers.machineNumbers-list', compact('machineNumbers'));
    }

    public function create()
    {
        return view('admin.machine-numbers.create');
    }

    public function store(Request $request) {
        request()->validate([
            'quantity' => 'required',
    	]);
        $quantity = $request->quantity;
		$status = $request->status;
		$i = 0;
		foreach($quantity as $row){
			$date = [
				'machine_number' => uniqid(),
				'quantity' => $row,
				'status' => $status[$i++],
				'created_at' => now()->toDateTimeString(),
				'updated_at' => now()->toDateTimeString(),
			];
			MachineNumbers::Create($date);
		}
        
        Alert::success('Machine Number', 'Added successfully');
        return redirect()->route('admin.machine-numbers.index')->with('message', 'Machine Number created successfully.');
    }

    public function edit($id)
    {
        $machineNumbers = MachineNumbers::select('machine_numbers.*','users.name as username','users.id as u_id')
            ->leftJoin('user_kyc_details as ky', 'ky.machine_number', '=', 'machine_numbers.machine_number')
            ->leftJoin('users', 'users.id', '=', 'ky.user_id')
            ->where('machine_numbers.id',$id)->first();

       	return view('admin.machine-numbers.edit', compact('machineNumbers'));
    }

    public function update(Request $request, $id){
        request()->validate([
            'quantity' => 'required',
	        'status' => 'required',
        ]);

	   $update = MachineNumbers::findOrFail($id);
        $update->quantity = $request->quantity;
        $update->status = $request->status;
        $update->save();
        Alert::success('Machine Number', 'Updated successfully'); 
        return redirect()->route('admin.machine-numbers.index')->with('message', 'Machine Number updated successfully.');
    }


    public function destroy($id) {
        MachineNumbers::where('id', $id)->delete();
        return redirect()->route('admin.machine-numbers.index')->withMessage('Deleted successfully!');
    }




    public function uploadMachineNumbers(Request $request) {
	request()->validate([
            'csv_import' => 'required|file',
                ], [
            'csv_import.required' => 'CSV file is required',
        ]);
        ini_set('memory_limi', -1);
        $uploadedFile = $request->file('csv_import');
        $extension = $uploadedFile->getClientOriginalExtension();
        if (strtolower($extension) != 'csv') {
            return redirect()->back()->with('error', 'Uploaded file is not CSV file.');
        }
        $inputFileName = $uploadedFile->move(public_path('uploads'), 'meternumbers.csv');
        if (!mb_check_encoding(file_get_contents($inputFileName), 'UTF-8')) {
            return redirect()->back()->with('error', 'Uploaded file is not UTF-8 formate.');
        }
        $spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($inputFileName);
        $rows = $spreadsheet->getSheet(0)->toArray();
        $headers = array_shift($rows);
        $data = $this->importMachineNumbers($rows);
        unlink($inputFileName);
        if (empty($data)) {
            Alert::success('Machine Numbers', 'Uploaded successfully');
            return redirect()->route('admin.machine-numbers.index')->with('message', 'Uploaded successfully.');
        } else {
            $error = implode(',', $data);
            Alert::error('Machine Numbers Error', 'Following row data not save ' . $error);
            return redirect()->route('admin.machine-numbers.index')->with('message', 'Following row data not save ' . $error);
        }
    }
    /* start machine number bulk upload add and update */
    public function importMachineNumbers($rows) {
        $bulk_serial_number_records = [];
        $error = null;
	
        foreach ($rows as $index => $value) {
            //dd($value);
            if (isset($value[0])) {
                $date = [
                    'customer_name' => $value[0],
		    'machine_number' => $value[1],
		    'quantity' => $value[2],
		    'plan' => $value[3],
		    'status' => $value[4],	
                    'created_at' => now()->toDateTimeString(),
                    'updated_at' => now()->toDateTimeString(),
                ];
                $bulk_serial_number_records[] = $date;
                $exist = MachineNumbers::where('machine_number', $value[0])->first();
                if (empty($exist)) {
                    MachineNumbers::Create($date);
                } else {
                    $error[] = $index + 2;
                }
            } else {
                $error[] = $index + 2;
            }
        }
        if (count($bulk_serial_number_records) > 0) {
		//            PlanSerialNumbers::insert($bulk_serial_number_records);
        }
        return $error;
    }
}

resources/views/admin/machine-numbers/create.blade.php
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
      <meta name="description" content="POS - Bootstrap Admin Template">
      <meta name="keywords" content="admin, estimates, bootstrap, business, corporate, creative, management, minimal, modern,  html5, responsive">
      <meta name="author" content="Dreamguys - Bootstrap Admin Template">
      <meta name="robots" content="noindex, nofollow">
      <title>{{ trans('global.create') }} Machine Numbers</title>
      
      <link rel="shortcut icon" type="image/x-icon" href="{{ asset('public/Admin/img/favicon.png')}}">
      
      <link rel="stylesheet" href="{{ asset('public/Admin/css/bootstrap.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/plugins/select2/css/select2.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/animate.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/dataTables.bootstrap4.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/plugins/fontawesome/css/fontawesome.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/plugins/fontawesome/css/all.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/style.css')}}">
      
   </head>
   <body>
      <div id="global-loader">
         <div class="whirly-loader"> </div>
      </div>
      <div class="main-wrapper">
        @extends('layouts.header')
     
        @extends('layouts.sidebar')
        
        <div class="page-wrapper">
            <div class="content container-fluid">
               <div class="page-header">
                  <div class="row">
                     <div class="col">
                        <h3 class="page-title">{{ trans('global.create') }} Machine Numbers</h3>
                        <ul class="breadcrumb">
                           <li class="breadcrumb-item"><a href="{{route('admin.home')}}">{{ trans('global.dashboard') }}</a></li>
                           <li class="breadcrumb-item"><a href="{{route('admin.machine-numbers.index')}}">Machine Numbers List</a></li>
                           <li class="breadcrumb-item active">Create Machine Numbers</li>
                        </ul>
                     </div>
                  </div>
               </div>
               <div class="row">
                  <div class="col-sm-12">
                     <div class="card">
                        <!-- <div class="card-header row">
                            <div class="col-lg-6"><h4 class="card-title">{{ trans('global.create') }} {{ trans('cruds.permission.title_singular') }}</h4></div>
                            
                        </div> -->
                        <div class="card-body">
							<a class="btn btn-success addnew"  >+</a>
                           <form action="{{ route('admin.machine-numbers.store') }}" method="POST">
                            {{ csrf_field() }}
                              <div class="row tr_clone_first tr_clone">
								  <div class="form-group col-md-6">
									 <label>Quantity</label>
									 <input type="number" name="quantity[]" id="quantity" class="form-control" placeholder="Machine Quantity" required="">
									 @if($errors->has('quantity')) <em class="invalid-feedback"> {{ $errors->first('quantity') }} </em> @endif
								  </div>
								  <div class="form-group col-md-6">
									<label>Status</label>
									<select name="status[]" id="status" class="form-control">
									  <option value="active"  >Active</option> 
									  <option value="deactive" >Deactive</option> 
									</select>
									@if($errors->has('status')) <em class="invalid-feedback"> {{ $errors->first('status') }} </em> @endif
								  </div>
							  </div>
                              <div>
                                 <button type="submit" class="btn btn-success">Save</button>
                              </div>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
    <script src="{{ asset('public/Admin/js/jquery-3.6.0.min.js')}}"></script>
    <script src="{{ asset('public/Admin/plugins/select2/js/select2.min.js')}}"></script>
   
    <script src="{{ asset('public/Admin/js/feather.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/jquery.slimscroll.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/script.js')}}"></script>
    <script>
		$(document).on('click', '.addnew', function(e){
			
			$(".tr_clone").append('<div class="row tr_clone_first"><div class="form-group col-md-6"><label>Quantity</label><input type="number" name="quantity[]" id="quantity" class="form-control" placeholder="Machine Quantity" required="">@if($errors->has("quantity")) <em class="invalid-feedback"> {{ $errors->first("quantity") }} </em> @endif</div><div class="form-group col-md-6"><label>Status</label><select name="status[]" id="status" class="form-control"><option value="active"  >Active</option><option value="deactive" >Deactive</option></select>@if($errors->has("status")) <em class="invalid-feedback"> {{ $errors->first("status") }} </em> @endif</div></div>');
			 
			
		});
	</script>
   </body>
</html>

resources/views/admin/machine-numbers/edit.blade.php
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
      <meta name="description" content="POS - Bootstrap Admin Template">
      <meta name="keywords" content="admin, estimates, bootstrap, business, corporate, creative, management, minimal, modern,  html5, responsive">
      <meta name="author" content="Dreamguys - Bootstrap Admin Template">
      <meta name="robots" content="noindex, nofollow">
      <title>{{ trans('global.edit') }} Machine Numbers</title>
      
      <link rel="shortcut icon" type="image/x-icon" href="{{ asset('public/Admin/img/favicon.png')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/bootstrap.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/animate.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/dataTables.bootstrap4.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/plugins/fontawesome/css/fontawesome.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/plugins/fontawesome/css/all.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/style.css')}}">
   </head>
   <body>
      <div id="global-loader">
         <div class="whirly-loader"> </div>
      </div>
      <div class="main-wrapper">
        @extends('layouts.header')
     
        @extends('layouts.sidebar')
        
        <div class="page-wrapper">
            <div class="content container-fluid">
               <div class="page-header">
                  <div class="row">
                     <div class="col">
                        <h3 class="page-title">Update Machine Numbers </h3>
                        <ul class="breadcrumb">
                           <li class="breadcrumb-item"><a href="{{route('admin.home')}}">{{ trans('global.dashboard') }}</a></li>
                           <li class="breadcrumb-item"><a href="{{ route('admin.machine-numbers.index') }}">Machine Numbers List</a></li>
                           <li class="breadcrumb-item active">Update Machine Numbers</li>
                        </ul>
                     </div>
                  </div>
               </div>
               <div class="row">
                  <div class="col-sm-12">
                     <div class="card">
                       <div class="card-body">
                           <form action="{{ route('admin.machine-numbers.update',$machineNumbers->id) }}" method="POST">
				                      {{ csrf_field() }} @method('PUT')
                                <div class="form-group">
                                	<label>Quantity</label>
	                                <input type="text" name="quantity" value="{{ $machineNumbers->quantity }}" id="quantity" class="form-control" placeholder="Machine Quantity" required="">
        	                        @if($errors->has('quantity')) <em class="invalid-feedback"> {{ $errors->first('quantity') }} </em> @endif
                                </div>
                        				<div class="form-group">
                        					<label>Status</label>
                        					<select name="status" id="status" class="form-control">
                        						<option value="active" {{ ($machineNumbers->status == 'active')? 'selected': '' }} >Active</option> 
                        						<option value="inactive" {{ ($machineNumbers->status == 'deactive')? 'selected': '' }}>Deactive</option> 
                        					</select>
                        					@if($errors->has('status')) <em class="invalid-feedback"> {{ $errors->first('status') }} </em> @endif
                        				</div>
                        				<div>
                        					<button type="submit" class="btn btn-success">Update</button>
                        				</div>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
    <script src="{{ asset('public/Admin/js/jquery-3.6.0.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/feather.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/jquery.slimscroll.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{ asset('public/Admin/plugins/apexchart/apexcharts.min.js')}}"></script>
    <script src="{{ asset('public/Admin/plugins/apexchart/chart-data.js')}}"></script>
    <script src="{{ asset('public/Admin/js/script.js')}}"></script>
   </body>
</html>

resources/views/admin/machine-numbers/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="breadcomb-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div class="breadcomb-list">
					<div class="row">
						<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
							<div class="breadcomb-wp">
								<div class="breadcomb-icon">
									<i class="notika-icon notika-windows"></i>
								</div>
								<div class="breadcomb-ctn">
                                    <h2>Show Complaint Feedback</h2>
                                    <p>Show <span class="bread-ntd">particular Complaint Feedback</span></p>
								</div>								
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-3">
                            <div class="breadcomb-report">
                                <a class="btn btn-success notika-btn-success waves-effect" href="{{ url()->previous() }}">
                                    {{ trans('global.back_to_list') }}
                                </a>
							</div>							
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="data-table-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="data-table-list">
                        <div class="table-responsive">
                            <table id="data-table-basic" class="table table-striped">
                            <tbody>
                                <tr>
                                    <th>Title</th>
                                    <td>{{ $complaintfeedback->title }}</td>
                                </tr>
                                <tr>
                                    <th>Type</th>
                                    <td>{{ $complaintfeedback->type }}({{$complaintfeedback->status}})</td>
                                </tr>
                                <tr>
                                    <th>Name</th>
                                    <td>{{ $complaintfeedback->user->name }}</td>
                                </tr>
                                <tr>
                                    <th>Date</th>
                                    <td>{{ $complaintfeedback->created_at->format('d M Y') }}</td>
                                </tr>
                                <tr>
                                    <th>Description</th>
                                    <td>{{ $complaintfeedback->description }}</td>
                                </tr>
                                @if($complaintfeedback->status == 'Solved')
                                <tr>
                                    <th>Comment</th>
                                    <td>{{ $complaintfeedback->comment }}</td>
                                </tr>
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection