routes/web.php
<?php

use App\Http\Controllers\Admin\LicensekeyController;

Route::get('/', function () {
    return redirect('/login');
});
Auth::routes(['register' => false]);
Auth::routes(['verify' => true]);

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::post('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');
Route::get('checkotp', 'Auth\ChangePasswordController@showOtpPasswordForm')->name('auth.checkOtp');
Route::post('checkotp', 'Auth\ChangePasswordController@chekOtpPassword')->name('auth.checkOtp');


Route::get('cache-clear', function () {
    \Artisan::call('config:cache');
    \Artisan::call('cache:clear');
    \Artisan::call('config:clear');
    \Artisan::call('view:clear');
    dd('cache-clear');
    return redirect('/');
});

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');
Route::get('otp-verify', 'Auth\RegisterController@showVerifyOtp')->name('otp-verify');
Route::post('otp-verify', 'Auth\RegisterController@verifyOtp')->name('otp-verify-submit');


Route::get('cron', 'Admin\CronController@index')->name('cron');
Route::get('cron/image', 'Admin\CronController@image')->name('cronimage');
Route::get('cron/plans', 'Admin\CronController@plans')->name('cronplans');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/like-list/{type}', 'HomeController@likeList')->name('like-list');
    Route::get('chart/getchatdata', 'HomeController@getchatdata');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::delete('permissions_mass_destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.mass_destroy');
    Route::resource('roles', 'Admin\RolesController');
    Route::delete('roles_mass_destroy', 'Admin\RolesController@massDestroy')->name('roles.mass_destroy');
    Route::resource('users', 'Admin\UsersController');
    Route::delete('users_mass_destroy', 'Admin\UsersController@massDestroy')->name('users.mass_destroy');
    Route::get('user-activity/{id}', 'Admin\UsersController@userActivity')->name('users.users_activity');

    /*** Plan and Recharge  **/
    Route::resource('planrecharge', 'Admin\PlanRechargeController');
    Route::get('changeStatusplanrecharge', 'Admin\PlanRechargeController@changeStatus');
    Route::delete('planrecharges_mass_destroy', 'Admin\PlanRechargeController@massDestroy')->name('planrecharge.mass_destroy');

    /*** plotter  **/
    Route::resource('plotter', 'Admin\PlotterController');
    Route::get('changeStatusplotter', 'Admin\PlotterController@changeStatus');
    Route::delete('plotters_mass_destroy', 'Admin\PlotterController@massDestroy')->name('plotter.mass_destroy');


    /*** Category (old brand-type) NT **/
    Route::resource('brand-type', 'Admin\BrandTypeController');
    Route::post('brand-type-order-position', 'Admin\BrandTypeController@brandTypeOrderPosition')->name('brandTypeOrderPosition');
    Route::get('changeStatusBrandType', 'Admin\BrandTypeController@changeStatus');
    Route::get('brand-type/delete/{id}', 'Admin\BrandTypeController@deleteBrandType');
    Route::delete('brand_types_mass_destroy', 'Admin\BrandTypeController@massDestroy')->name('brandtype.mass_destroy');
    Route::get('brand-type-list', 'Admin\BrandTypeController@brandTypeDetails')->name('brand-type-list');

    /*** Brand NT **/
    Route::resource('brands', 'Admin\BrandController');
    Route::post('brand-order-position', 'Admin\BrandController@brandOrderPosition')->name('brandOrderPosition');
    Route::get('changeStatusBrand', 'Admin\BrandController@changeStatus');
    Route::get('brand/delete/{id}', 'Admin\BrandController@deleteBrand');
    Route::delete('brands_mass_destroy', 'Admin\BrandController@massDestroy')->name('brands.mass_destroy');
    //Route::get('brand-list', 'Admin\BrandController@brandDetails')->name('brand-list');
    Route::get('brandsdetails/{id}', 'Admin\BrandController@brandDetails')->name('brands.brandsdetails');


    /*** BrandModel NT **/
    Route::resource('models', 'Admin\BrandModelController');
    Route::post('models-order-position', 'Admin\BrandModelController@modelsOrderPosition')->name('modelsOrderPosition');
    Route::get('changeStatus', 'Admin\BrandModelController@changeStatus');
    Route::get('models/delete/{id}', 'Admin\BrandModelController@deleteModel');
    Route::delete('models_mass_destroy', 'Admin\BrandModelController@massDestroy')->name('models.mass_destroy');
    Route::get('modelsdetails/{id}', 'Admin\BrandModelController@modelsDetails')->name('models.modelsDetails');

    Route::get('get-brand-type-list', 'Admin\BrandModelController@getBrandTypes');
    Route::get('get-model-list', 'Admin\BrandModelController@getModelList');

    /*** Brand Submodel NT **/
    Route::resource('submodels', 'Admin\BrandSubModelController');
    Route::post('submodels-order-position', 'Admin\BrandSubModelController@submodelsOrderPosition')->name('submodelsOrderPosition');
    Route::get('changeSubmodelStatus', 'Admin\BrandSubModelController@changeStatus');
    Route::get('deleteSubModel/{id}', 'Admin\BrandSubModelController@deleteSubModel');
    Route::delete('submodels_mass_destroy', 'Admin\BrandSubModelController@massDestroy')->name('submodels.mass_destroy');
    Route::get('submodelDetails/{id}', 'Admin\BrandSubModelController@submodelDetails')->name('submodels.submodelDetails');

    Route::get('get-sub-brand-type-list', 'Admin\BrandSubModelController@getBrandTypes');

    /*** BrandModelScreenImageController **/
    Route::resource('models-screen-image', 'Admin\BrandModelScreenImageController');
    Route::post('models-screen-image-order-position', 'Admin\BrandModelScreenImageController@modelsScreenImageOrderPosition')->name('modelsScreenImageOrderPosition');
    Route::get('changeStatusModelScreen', 'Admin\BrandModelScreenImageController@changeStatusModelScreen');
    //Route::get('deleteModelScreenBltFiles', 'Admin\BrandModelScreenImageController@deleteModelScreenBltFiles');
    Route::get('deleteModelScreenImage', 'Admin\BrandModelScreenImageController@deleteModelScreenImage');
    Route::get('deleteModelScreenBltFiles/{id}', 'Admin\BrandModelScreenImageController@deleteModelScreenBltFiles');
    Route::delete('models_screen_image_mass_destroy', 'Admin\BrandModelScreenImageController@massDestroy')->name('models-screen-image.mass_destroy');
    Route::get('models-screen-image-list', 'Admin\BrandModelScreenImageController@modelScreenImageDetails')->name('models-screen-image-list');
    Route::get('deleteModelScreen/{id}', 'Admin\BrandModelScreenImageController@deleteModelScreen');


    Route::get('get-brand-list', 'Admin\BrandModelScreenImageController@getBrand');
    Route::post('addMoreImage', 'Admin\BrandModelScreenImageController@addMoreImage');

    /*** Bulk Upload NT **/
    Route::get('bulkupload', 'Admin\BulkUploadController@create')->name('bulkupload.create');
    Route::post('bulkupload/store', 'Admin\BulkUploadController@store')->name('bulkupload.store');
    Route::post('bulk-export', 'Admin\BulkUploadController@export')->name('bulkupload.export');

    /*** Retailers **/
    Route::resource('retailers', 'Admin\RetailerController');
    Route::post('retailers-list-deleteall', 'Admin\RetailerController@retailerDeleteAll');

    /*** Plans NT **/
    Route::resource('plans', 'Admin\PlanController');
    Route::get('changeStatusPlan', 'Admin\PlanController@changeStatus');
    Route::get('plan/delete/{id}', 'Admin\PlanController@deletePlan');
    Route::delete('plans_mass_destroy', 'Admin\PlanController@massDestroy')->name('plans.mass_destroy');
    Route::post('upload/serialnumber/{id}', 'Admin\PlanController@uploadSerialNumbers')->name('plans.upload.serialnumber');


    Route::resource('serial-numbers', 'Admin\SerialNumbersController');

    Route::resource('machine-numbers', 'Admin\MachineNumbersController');
    Route::post('upload/machinenumber', 'Admin\MachineNumbersController@uploadMachineNumbers')->name('upload.machinenumber');

    /*** Indivisual user commission change  NT **/
    Route::post('plan/change/{id}', 'Admin\RetailerController@changeCurrentPlan')->name('planChangeAdmin');

    /*customer Recharge Commission NT26022121*/
    Route::get('customer-recharge-commission', 'Admin\RetailerController@customerRechargeCommission')->name('customer-recharge-commission');
    Route::get('customer-recharge-commission-report', 'Admin\RetailerController@customerRechargeCommissionReport')->name('customer-recharge-commission-report');

    /*customer profile change NT26022121*/
    Route::get('retailer-profile-change-request', 'Admin\RetailerController@retailerProfileChangeRequestList')->name('retailer-profile-change-request');
    Route::get('change-profile-request-status', 'Admin\RetailerController@changeProfileRequestStatus');

    /*customer imei change request list and update NT26022121*/
    Route::get('imei-change-request-list', 'Admin\RetailerController@imeiChangeRequestList')->name('imei-change-request');
    Route::get('update-imei-request/{id}', 'Admin\RetailerController@updateImeiRequest');

    /*Currency show and update NT04032121*/
    Route::get('setting/currency', 'Admin\SettingController@currencySetting')->name('setting.currency');
    Route::get('setting/website', 'Admin\SettingController@websiteSetting')->name('setting.website');
    Route::get('setting/otpprice', 'Admin\SettingController@otppriceSetting')->name('setting.otpprice');
    Route::put('setting/otpprice-update', 'Admin\SettingController@otppriceUpdate')->name('setting.otpprice-update');
    Route::put('setting/currency-update', 'Admin\SettingController@updateCurrencySetting')->name('setting.currency-update');

app/Models/PlanRecharge.php
<?php

namespace App\Models;
use App\Models\Brands;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class PlanRecharge extends Model
{
   use SoftDeletes;
   protected $guarded = [];

   protected $fillable = ['name','category', 'amount', 'yearly_charges','plotter','speed','pressure','status'];
   
   

   
}

app/Http/Controllers/Admin/PlanRechargeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Plotter;
use App\Models\PlanRecharge;
use App\Models\BrandType;

use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Str;
use DB;
Use Alert;
use Symfony\Component\HttpFoundation\Response;

class PlanRechargeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
		
		$planrecharges_data = PlanRecharge::orderBy('id','DESC')->select(DB::raw('CONCAT(id,"_",status) AS id_status'),'id','name','category','amount','yearly_charges','plotter','speed','pressure','status','created_at')->get();
		$planrecharges = [];
		foreach($planrecharges_data as $row){
			
			$row->category = json_decode($row->category);
			$category = BrandType::whereIn("id",$row->category)->select("id","name")->get();
			
			$row->plotter = json_decode($row->plotter);
			$plotter = Plotter::whereIn("id",$row->plotter)->select("id","name")->get();
			
			array_push($planrecharges,
				array(
					"id" => $row->id,
					"id_status" => $row->id_status,
					"name" => $row->name,
					"category" => $category,
					"amount" => $row->amount,
					"yearly_charges" => $row->yearly_charges,
					"plotter" => $plotter,
					"speed" => json_decode($row->speed),
                    "pressure" => json_decode($row->pressure),
					"status" => $row->status,
					"created_at" => $row->created_at,
				)
			);
		}
       
       return view('admin.plan-recharge.index', compact('planrecharges'));
    }
	
	/**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
		$brandTypes = BrandType::get();
		$plotters = Plotter::get();
        return view('admin.plan-recharge.create',compact('brandTypes','plotters'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
		/* dd($request); */
        $validated = $request->validate([
			'name' => 'required|min:2',
			'categories' => 'required',
			'amount' => 'required',
			'yearly_charges' => 'required',
			// 'plotter' => 'required',
			'plotter_arr_ids' => 'required',
			'plotter_speed_arr' => 'required',
			'status'=>'required'
		]); 
		
		$planrecharge = new PlanRecharge();
		$planrecharge->name = $request->name;
		$planrecharge->category	 = json_encode($request->categories);
		$planrecharge->amount = $request->amount;
		$planrecharge->yearly_charges = $request->yearly_charges;
		$planrecharge->plotter = json_encode($request->plotter_arr_ids);                     
		$planrecharge->speed = json_encode($request->plotter_speed_arr);
        $planrecharge->pressure = json_encode($request->plotter_pressure_arr);                     
		$planrecharge->status = $request->status;                     
		$planrecharge->save();
		
		Alert::success('PlanRecharge', 'Added successfully');
		return redirect()->route('admin.planrecharge.index')->with('message', 'Plan Recharge created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,$id)
    {
		$planrecharge = PlanRecharge::findOrFail($id);
		$category_arr = json_decode($planrecharge->category);
		$plotter_arr = json_decode($planrecharge->plotter);
		
		$category = BrandType::whereIn("id",$category_arr)->select("id","name")->get();
		$plotter = Plotter::whereIn("id",$plotter_arr)->select("id","name")->get();
        
		return view('admin.plan-recharge.show', compact('planrecharge','category','plotter'));
    }
	
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
     
        $planrecharge = PlanRecharge::findOrFail($id);
		$category_arr = json_decode($planrecharge->category);
		$plotter_arr = json_decode($planrecharge->plotter);
		
		$category = BrandType::whereIn("id",$category_arr)->select("id","name")->get()->toArray();
		$category_ids = array_column($category,'id');
		$plotter_name_id = Plotter::whereIn("id",$plotter_arr)->select("id","name", "speed", "pressure")->get()->toArray();
		$plotter_ids = array_column($plotter_name_id,'id');
		
		$brandTypes = BrandType::get();
		$plotters = Plotter::get();
		
		return view('admin.plan-recharge.edit', compact('planrecharge','brandTypes','plotters','category_ids','plotter_ids','plotter_name_id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
		
        $validated = $request->validate([
			'name' => 'required|min:2',
			'categories' => 'required',
			'amount' => 'required',
			'yearly_charges' => 'required',
			// 'plotter' => 'required',
			'plotter_arr_ids' => 'required',
			'plotter_speed_arr' => 'required',
			'status'=>'required'
		]); 
			
		$planrecharge = PlanRecharge::findOrFail($id);
		$planrecharge->name = $request->name;
		$planrecharge->category	 = json_encode($request->categories);
		$planrecharge->amount = $request->amount;
		$planrecharge->yearly_charges = $request->yearly_charges;
		$planrecharge->plotter = json_encode($request->plotter_arr_ids);                     
		$planrecharge->speed = json_encode($request->plotter_speed_arr);
        $planrecharge->pressure = json_encode($request->plotter_pressure_arr);                     
		$planrecharge->status = $request->status;                     
		$planrecharge->save();
		
		
		Alert::success('PlanRecharge', 'updated successfully');
		return redirect()->route('admin.planrecharge.index')->with('message', 'PlanRecharge updated successfully.');
		
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
	 
	public function destroy($id) {
		
        $data = PlanRecharge::find($id);
				
        if($data->delete()){
			return redirect()->route('admin.planrecharge.index')->withMessage('Deleted successfully!');
        } else{
            $error = "Something wrong! Please try later ";            
            return back()->with('message', 'Something wrong! Please try later.');
        }
    }
	
    public function changeStatus(Request $request)
	{       
		$planrecharge = PlanRecharge::find($request->id);
		$planrecharge->status = $request->status;
        $planrecharge->save();
		return response()->json(['success'=>'Status change successfully.']);
	}

    public function massDestroy(Request $request)
    {
        
        $ids = $request->ids;
		
        PlanRecharge::whereIn('id',explode(",",$ids))->delete();
        return response()->json(['success'=>'Deleted successfully']);
    }

}

resources/views/admin/plan-recharge/create.blade.php
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
		<meta name="description" content="POS - Bootstrap Admin Template">
		<meta name="keywords" content="admin, estimates, bootstrap, business, corporate, creative, management, minimal, modern,  html5, responsive">
		<meta name="author" content="Dreamguys - Bootstrap Admin Template">
		<meta name="robots" content="noindex, nofollow">
		<title>Create Plan Recharge</title>
      
		<link rel="shortcut icon" type="image/x-icon" href="{{ asset('public/Admin/img/favicon.png')}}">
		<link rel="stylesheet" href="{{ asset('public/Admin/css/bootstrap.min.css')}}">
		<link rel="stylesheet" href="{{ asset('public/Admin/plugins/select2/css/select2.min.css')}}">
		<link rel="stylesheet" href="{{ asset('public/Admin/css/animate.css')}}">
		<link rel="stylesheet" href="{{ asset('public/Admin/css/dataTables.bootstrap4.min.css')}}">
		<link rel="stylesheet" href="{{ asset('public/Admin/plugins/fontawesome/css/fontawesome.min.css')}}">
		<link rel="stylesheet" href="{{ asset('public/Admin/plugins/fontawesome/css/all.min.css')}}">
		<link rel="stylesheet" href="{{ asset('public/Admin/css/style.css')}}">
	</head>
	<body>
		<div id="global-loader">
			<div class="whirly-loader"> </div>
		</div>
		<div class="main-wrapper">
			@extends('layouts.header')
			@extends('layouts.sidebar')
        	<div class="page-wrapper">
				<div class="content container-fluid">
					<div class="page-header">
						<div class="row">
							<div class="col">
								<h3 class="page-title">Create Plan Recharge</h3>
								<ul class="breadcrumb">
								   <li class="breadcrumb-item"><a href="{{route('admin.home')}}">{{ trans('global.dashboard') }}</a></li>
								   <li class="breadcrumb-item"><a href="{{ route('admin.planrecharge.index') }}">Plan Recharges</a></li>
								   <li class="breadcrumb-item active">Create Plan Recharge</li>
								</ul>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<div class="card">
								<div class="card-body">
									<form action="{{ route('admin.planrecharge.store') }}" method="POST" enctype="multipart/form-data">
										{{ csrf_field() }}
										<div class="form-group">
											<label>Name<span class="text-danger">*</span></label>
											<input type="text" class="form-control @error('name') is-invalid @enderror" value="{{ old('name') }}" placeholder="Name*" id="name" name="name" required>
											@if($errors->has('name')) 
												<em class="invalid-feedback"> {{ $errors->first('name') }} </em> 
											@endif
										</div>
										<div class="form-group ">
											<label>Categories<span class="text-danger">*</span></label>
											<select class="form-control @error('categories') is-invalid @enderror" name="categories[]" id="categories" multiple  placeholder="Categories*" required>
												@foreach($brandTypes as $id => $brandType)
													<option value="{{ $brandType->id }}" {{ (in_array($id, old('categories', [])) || isset($plan) && $plan->PlanBrandTypes()->pluck('brand_type_id')->contains($brandType->id)) ? 'selected' : '' }}>{{ $brandType->name }} </option>
												@endforeach
											</select>
											@if ($errors->has('categories'))
												<span class="text-danger">{{ $errors->first('categories') }}</span>
											@endif
										</div>
										<div class="form-group">
											<label>Amount<span class="text-danger">*</span></label>
											<input type="text" class="form-control @error('amount') is-invalid @enderror" value="{{ old('amount') }}" placeholder="Amount*" id="amount" name="amount" required>
											@if($errors->has('amount')) 
												<em class="invalid-feedback"> {{ $errors->first('amount') }} </em> 
											@endif
										</div>
										<div class="form-group">
											<label>Yearly Charges<span class="text-danger">*</span></label>
											<input type="text" class="form-control @error('yearly_charges') is-invalid @enderror" value="{{ old('yearly_charges') }}" placeholder="Yearly Charges*" id="yearly_charges" name="yearly_charges" required>
											@if($errors->has('yearly_charges')) 
												<em class="invalid-feedback"> {{ $errors->first('yearly_charges') }} </em> 
											@endif
										</div>
										<div class="form-group">
											<label>Status<span class="text-danger">*</span></label>
											<select class="form-control @error('status') is-invalid @enderror" name="status">
												<option value="" >Select Status</option>
												<option value="1" {{ (old('status') == '1' )? 'selected': ''}}>Enable</option>
												<option value="0" {{ (old('status') == '0') ? 'selected': ''}}>Disable</option>
											</select>
											@if($errors->has('status')) 
												<em class="invalid-feedback"> {{ $errors->first('status') }} </em> 
											@endif
										</div>
										<div class="form-group ">
											<label>Plotters<span class="text-danger">*</span></label>
                                            @foreach($plotters as $id => $plotter)
												<table class="table">
														<tr><td style="width:18%; line-height:1;" ><strong>{{ $plotter->name }}</strong><input type='hidden' name='plotter_arr_ids[]' value="{{ $plotter->id }}"></td><td style="width:25%;">Max. Speed : {{ $plotter->speed }} <br> Max. Pressure : {{ $plotter->pressure }}</td><td style="width:25%;"><input type='number' class="form-control" name='plotter_speed_arr[]' min="0" max='{{ $plotter->speed }}' placeholder="Max. Speed" required></td><td style="width:25%;"><input type='number' class="form-control" name='plotter_pressure_arr[]' min="0" max='{{ $plotter->pressure }}' placeholder="Max. Pressure" required></td></tr>
													</table>
											@endforeach
										
											@if ($errors->has('plotter'))
												<span class="text-danger">{{ $errors->first('plotter') }}</span>
											@endif
										</div>
										
										<div class="mb-2">
											<button type="submit" class="btn btn-success">Save</button>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<script src="{{ asset('public/Admin/js/jquery-3.6.0.min.js')}}"></script>
		<script src="{{ asset('public/Admin/plugins/select2/js/select2.min.js')}}"></script>
		<script src="{{ asset('public/Admin/plugins/select2/js/custom-select.js')}}"></script>
		<script src="{{ asset('public/Admin/js/feather.min.js')}}"></script>
		<script src="{{ asset('public/Admin/js/jquery.slimscroll.min.js')}}"></script>
		<script src="{{ asset('public/Admin/js/bootstrap.bundle.min.js')}}"></script>
		<script src="{{ asset('public/Admin/js/script.js')}}"></script>
		
		<script>
			$("#plotter").change(function(){
				var speed = [];
				$("input[name='plotter_speed_arr[]']").each(function() {
					speed.push($(this).val());
				});
				console.log(speed);
				$("#add_plotter").html("");
				var i =0;
				$("#plotter :selected").each(function() {
					$("#add_plotter").append("<tr><td><input type='hidden' name='plotter_arr_ids[]' value='"+this.value+"'><input type='text' name='plotter_arr[]' value='"+this.text+"' style='cursor: default;background-color: -internal-light-dark(rgba(239, 239, 239, 0.3), rgba(59, 59, 59, 0.3));color: -internal-light-dark(rgb(84, 84, 84), rgb(170, 170, 170));border-color: rgba(118, 118, 118, 0.3);' readonly disabled></td><td><input type='text' name='plotter_speed_arr[]' required value='"+(speed[i++] ?? '' )+"'></td></tr>");
				});
				
				
			});
			$(document).ready(function() {
				$('#categories').select2();
				$('#plotter').select2();
			});
			
		</script>
	</body>
</html>