routes/web.php
    Route::get('/like-list/{type}', 'HomeController@likeList')->name('like-list');
    Route::get('chart/getchatdata', 'HomeController@getchatdata');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::delete('permissions_mass_destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.mass_destroy');
    Route::resource('roles', 'Admin\RolesController');
    Route::delete('roles_mass_destroy', 'Admin\RolesController@massDestroy')->name('roles.mass_destroy');
    Route::resource('users', 'Admin\UsersController');
    Route::delete('users_mass_destroy', 'Admin\UsersController@massDestroy')->name('users.mass_destroy');
    Route::get('user-activity/{id}', 'Admin\UsersController@userActivity')->name('users.users_activity');

    /*** Plan and Recharge  **/
    Route::resource('planrecharge', 'Admin\PlanRechargeController');
    Route::get('changeStatusplanrecharge', 'Admin\PlanRechargeController@changeStatus');
    Route::delete('planrecharges_mass_destroy', 'Admin\PlanRechargeController@massDestroy')->name('planrecharge.mass_destroy');

    /*** plotter  **/
    Route::resource('plotter', 'Admin\PlotterController');
    Route::get('changeStatusplotter', 'Admin\PlotterController@changeStatus');
    Route::delete('plotters_mass_destroy', 'Admin\PlotterController@massDestroy')->name('plotter.mass_destroy');


    /*** Category (old brand-type) NT **/
    Route::resource('brand-type', 'Admin\BrandTypeController');
    Route::post('brand-type-order-position', 'Admin\BrandTypeController@brandTypeOrderPosition')->name('brandTypeOrderPosition');
    Route::get('changeStatusBrandType', 'Admin\BrandTypeController@changeStatus');
    Route::get('brand-type/delete/{id}', 'Admin\BrandTypeController@deleteBrandType');
    Route::delete('brand_types_mass_destroy', 'Admin\BrandTypeController@massDestroy')->name('brandtype.mass_destroy');
    Route::get('brand-type-list', 'Admin\BrandTypeController@brandTypeDetails')->name('brand-type-list');

    /*** Brand NT **/
    Route::resource('brands', 'Admin\BrandController');
    Route::post('brand-order-position', 'Admin\BrandController@brandOrderPosition')->name('brandOrderPosition');
    Route::get('changeStatusBrand', 'Admin\BrandController@changeStatus');
    Route::get('brand/delete/{id}', 'Admin\BrandController@deleteBrand');
    Route::delete('brands_mass_destroy', 'Admin\BrandController@massDestroy')->name('brands.mass_destroy');
    //Route::get('brand-list', 'Admin\BrandController@brandDetails')->name('brand-list');
    Route::get('brandsdetails/{id}', 'Admin\BrandController@brandDetails')->name('brands.brandsdetails');


    /*** BrandModel NT **/
    Route::resource('models', 'Admin\BrandModelController');
    Route::post('models-order-position', 'Admin\BrandModelController@modelsOrderPosition')->name('modelsOrderPosition');
    Route::get('changeStatus', 'Admin\BrandModelController@changeStatus');
    Route::get('models/delete/{id}', 'Admin\BrandModelController@deleteModel');
    Route::delete('models_mass_destroy', 'Admin\BrandModelController@massDestroy')->name('models.mass_destroy');
    Route::get('modelsdetails/{id}', 'Admin\BrandModelController@modelsDetails')->name('models.modelsDetails');

    Route::get('get-brand-type-list', 'Admin\BrandModelController@getBrandTypes');
    Route::get('get-model-list', 'Admin\BrandModelController@getModelList');

    /*** Brand Submodel NT **/
    Route::resource('submodels', 'Admin\BrandSubModelController');
    Route::post('submodels-order-position', 'Admin\BrandSubModelController@submodelsOrderPosition')->name('submodelsOrderPosition');
    Route::get('changeSubmodelStatus', 'Admin\BrandSubModelController@changeStatus');
    Route::get('deleteSubModel/{id}', 'Admin\BrandSubModelController@deleteSubModel');
    Route::delete('submodels_mass_destroy', 'Admin\BrandSubModelController@massDestroy')->name('submodels.mass_destroy');
    Route::get('submodelDetails/{id}', 'Admin\BrandSubModelController@submodelDetails')->name('submodels.submodelDetails');

    Route::get('get-sub-brand-type-list', 'Admin\BrandSubModelController@getBrandTypes');

    /*** BrandModelScreenImageController **/
    Route::resource('models-screen-image', 'Admin\BrandModelScreenImageController');
    Route::post('models-screen-image-order-position', 'Admin\BrandModelScreenImageController@modelsScreenImageOrderPosition')->name('modelsScreenImageOrderPosition');
    Route::get('changeStatusModelScreen', 'Admin\BrandModelScreenImageController@changeStatusModelScreen');
    //Route::get('deleteModelScreenBltFiles', 'Admin\BrandModelScreenImageController@deleteModelScreenBltFiles');
    Route::get('deleteModelScreenImage', 'Admin\BrandModelScreenImageController@deleteModelScreenImage');
    Route::get('deleteModelScreenBltFiles/{id}', 'Admin\BrandModelScreenImageController@deleteModelScreenBltFiles');
    Route::delete('models_screen_image_mass_destroy', 'Admin\BrandModelScreenImageController@massDestroy')->name('models-screen-image.mass_destroy');
    Route::get('models-screen-image-list', 'Admin\BrandModelScreenImageController@modelScreenImageDetails')->name('models-screen-image-list');
    Route::get('deleteModelScreen/{id}', 'Admin\BrandModelScreenImageController@deleteModelScreen');


    Route::get('get-brand-list', 'Admin\BrandModelScreenImageController@getBrand');
    Route::post('addMoreImage', 'Admin\BrandModelScreenImageController@addMoreImage');

    /*** Bulk Upload NT **/
    Route::get('bulkupload', 'Admin\BulkUploadController@create')->name('bulkupload.create');
    Route::post('bulkupload/store', 'Admin\BulkUploadController@store')->name('bulkupload.store');
    Route::post('bulk-export', 'Admin\BulkUploadController@export')->name('bulkupload.export');

    /*** Retailers **/
    Route::resource('retailers', 'Admin\RetailerController');
    Route::post('retailers-list-deleteall', 'Admin\RetailerController@retailerDeleteAll');

    /*** Plans NT **/
    Route::resource('plans', 'Admin\PlanController');
    Route::get('changeStatusPlan', 'Admin\PlanController@changeStatus');
    Route::get('plan/delete/{id}', 'Admin\PlanController@deletePlan');
    Route::delete('plans_mass_destroy', 'Admin\PlanController@massDestroy')->name('plans.mass_destroy');
    Route::post('upload/serialnumber/{id}', 'Admin\PlanController@uploadSerialNumbers')->name('plans.upload.serialnumber');


    Route::resource('serial-numbers', 'Admin\SerialNumbersController');

    Route::resource('machine-numbers', 'Admin\MachineNumbersController');
    Route::post('upload/machinenumber', 'Admin\MachineNumbersController@uploadMachineNumbers')->name('upload.machinenumber');

    /*** Indivisual user commission change  NT **/
    Route::post('plan/change/{id}', 'Admin\RetailerController@changeCurrentPlan')->name('planChangeAdmin');

    /*customer Recharge Commission NT26022121*/
    Route::get('customer-recharge-commission', 'Admin\RetailerController@customerRechargeCommission')->name('customer-recharge-commission');
    Route::get('customer-recharge-commission-report', 'Admin\RetailerController@customerRechargeCommissionReport')->name('customer-recharge-commission-report');

    /*customer profile change NT26022121*/
    Route::get('retailer-profile-change-request', 'Admin\RetailerController@retailerProfileChangeRequestList')->name('retailer-profile-change-request');
    Route::get('change-profile-request-status', 'Admin\RetailerController@changeProfileRequestStatus');

    /*customer imei change request list and update NT26022121*/
    Route::get('imei-change-request-list', 'Admin\RetailerController@imeiChangeRequestList')->name('imei-change-request');
    Route::get('update-imei-request/{id}', 'Admin\RetailerController@updateImeiRequest');

    /*Currency show and update NT04032121*/
    Route::get('setting/currency', 'Admin\SettingController@currencySetting')->name('setting.currency');
    Route::get('setting/website', 'Admin\SettingController@websiteSetting')->name('setting.website');
    Route::get('setting/otpprice', 'Admin\SettingController@otppriceSetting')->name('setting.otpprice');
    Route::put('setting/otpprice-update', 'Admin\SettingController@otppriceUpdate')->name('setting.otpprice-update');
    Route::put('setting/currency-update', 'Admin\SettingController@updateCurrencySetting')->name('setting.currency-update');

    Route::post('addShopGallery', 'Admin\RetailerController@addShopGallery');
    Route::get('deleteShopGallery', 'Admin\RetailerController@deleteShopGallery');
    Route::get('get-state-list', 'Admin\UsersController@getStateList');
    Route::get('kyc/changeStatus', 'Admin\RetailerController@approveKyc');
    Route::post('kyc/adminChangeStatus', 'Admin\RetailerController@approveKycAdmin');

    Route::resource('recharge-plan', 'Admin\RechargePlanController');
    Route::get('recharge-plan/delete/{id}', 'Admin\RechargePlanController@deleteRechargePlan');
    Route::get('changeStatusRechargePlan', 'Admin\RechargePlanController@changeStatus');
    Route::resource('video', 'Admin\VideoController');
    Route::post('video-order-position', 'Admin\VideoController@videoOrderPosition')->name('videoOrderPosition');
    Route::get('video/delete/{id}', 'Admin\VideoController@deleteVideo');

    Route::resource('video-category', 'Admin\VideoCategoryController');
    Route::post('video-category-order-position', 'Admin\VideoCategoryController@videoCategoryOrderPosition')->name('videoCategoryOrderPosition');
    Route::get('video-category/delete/{id}', 'Admin\VideoCategoryController@deleteVideoCategory');
    Route::get('changeStatusVideoCategory', 'Admin\VideoCategoryController@changeStatus');

    /*PaperSizeController NT09031644*/
    /*Route::resource('/paper-size', 'Admin\PaperSizeController');
    Route::get('/paper-size/delete/{id}', 'Admin\PaperSizeController@deletePaperSize');
    Route::get('/changeStatusPaperSize/', 'Admin\PaperSizeController@changeStatus');
    */

resources/views/admin/submodels/create.blade.php
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
      <meta name="description" content="POS - Bootstrap Admin Template">
      <meta name="keywords" content="admin, estimates, bootstrap, business, corporate, creative, management, minimal, modern,  html5, responsive">
      <meta name="author" content="Dreamguys - Bootstrap Admin Template">
      <meta name="robots" content="noindex, nofollow">
      <title>Create Sub-Model</title>
      
      <link rel="shortcut icon" type="image/x-icon" href="{{ asset('public/Admin/img/favicon.png')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/bootstrap.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/animate.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/dataTables.bootstrap4.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/plugins/fontawesome/css/fontawesome.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/plugins/fontawesome/css/all.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/style.css')}}">
   </head>
   <body>
      <div id="global-loader">
         <div class="whirly-loader"> </div>
      </div>
      <div class="main-wrapper">
        @extends('layouts.header')
     
        @extends('layouts.sidebar')
        <div class="page-wrapper">
            <div class="content container-fluid">
                <div class="page-header">
					<div class="row">
						<div class="col">
							<h3 class="page-title">Create Sub-Model</h3>
							<ul class="breadcrumb">
								<li class="breadcrumb-item"><a href="{{route('admin.home')}}">{{ trans('global.dashboard') }}</a></li>
								<li class="breadcrumb-item">
									@if($selected_model->id)
										<a href="{{ route('admin.submodels.show',$selected_model->id) }}">Sub-Models</a>
									@else
										<a href="{{ route('admin.brand-type.index') }}">Sub-Models</a>
									@endif
								</li>
								<li class="breadcrumb-item active">Create Sub-Model</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-12">
						<div class="card">
							<div class="card-body">
								<form action="{{ route('admin.submodels.store') }}" method="POST" enctype="multipart/form-data">
									{{ csrf_field() }}
									<input type="hidden" name="get_model_id" value="{{ $selected_model->id }}">
									<div class="form-group">
										<label>Category<span class="text-danger">*</span></label>
										<select class="form-control @error('brand_type_id') is-invalid @enderror" name="brand_type_id" id="brand_type_id"  >
											<option value="">Select Category</option>
											@foreach($brand_types as $id => $brand_type)
												<option value="{{ $brand_type->id }}" {{ $selected_model->brand_type_id == $brand_type->id ? 'selected' : '' }} >{{ $brand_type->name }}</option>
											@endforeach
										</select>
										@if($errors->has('brand_type_id'))
											<em class="invalid-feedback">{{ $errors->first('brand_type_id') }}</em>
										@endif
									</div>
									<div class="form-group">
										<label>Brands<span class="text-danger">*</span></label>
										<select class="form-control @error('brand_id') is-invalid @enderror" name="brand_id" id="brand_id">
											<option value="">Select Brand </option>
											@foreach($brands as $id => $brand)
												<option value="{{ $brand->id }}" {{  $selected_model->brand_id == $brand->id ? 'selected' : '' }} >{{ $brand->name }}</option>
											@endforeach
										</select>
										@if($errors->has('brand_id'))
											<em class="invalid-feedback">{{ $errors->first('brand_id') }}</em>
										@endif
									</div>
									<div class="form-group">
										<label>Models<span class="text-danger">*</span></label>
										<select class="form-control @error('brand_models_id') is-invalid @enderror" name="brand_models_id" id="brand_models_id"   >
											<option value="">Select Model </option>
											@foreach($models as $id => $model)
											<option value="{{ $model->id }}" {{ $selected_model->id == $model->id ?'selected': '' }} >{{ $model->name }}</option>
											@endforeach
										</select>
										@if($errors->has('brand_models_id'))
											<em class="invalid-feedback">{{ $errors->first('brand_models_id') }}</em>
										@endif
									</div>
									<div class="form-group">
										<label>Sub-model Name<span class="text-danger">*</span></label>
										<input type="text" class="form-control @error('name') is-invalid @enderror" value="{{ old('name') }}" placeholder="Sub Model Name" id="name" name="name">
										@if($errors->has('name'))<span class="text-danger">{{ $errors->first('name') }}</span>@endif
									</div>
									<div class="form-group">
										<label>Cut Point</label>
										<input type="number" class="form-control" placeholder="Cut Point" value="{{ old('cut_point') }}" id="cut_point" name="cut_point" min="0">
									</div>
									<div class="form-group">
										<label>Upload image</label>
										<input type="file" accept="image/*" class="form-control" name="fileUpload" id="inputImage">
										<span id="preview"></span>
									</div>
									<div class="form-group">
										<label>Status<span class="text-danger">*</span></label>
										<select class="form-control @error('status') is-invalid @enderror" name="status" id="status" >
											<option value="" {{ old('status') == '' ? 'selected' : '' }}>Select Status</option>
											<option value="0" {{ old('status') == '0' ? 'selected' : '' }} >Inactive</option>
											<option value="1" {{ old('status') == '1' ? 'selected' : '' }}>Active</option>
										</select> 
										@if($errors->has('status'))<span class="text-danger">{{ $errors->first('status') }}</span>@endif										
									</div>
									<div class="form-group">
										<label>Meta Title</label>
										<input type="text" class="form-control" placeholder="Meta Title" id="metaTitle" name="metaTitle" value="{{ old('metaTitle') }}">
										@if($errors->has('metaTitle')) <em class="invalid-feedback"> {{ $errors->first('metaTitle') }} </em> @endif
									</div>
									<div class="form-group">
										<label>Meta Keyword</label>
										<input type="text" class="form-control"  placeholder="Meta Keyword" id="metaKeyword" name="metaKeyword" value="{{ old('metaKeyword') }}">
										@if($errors->has('metaKeyword')) <em class="invalid-feedback"> {{ $errors->first('metaKeyword') }} </em> @endif
									</div>
									<div class="form-group">
										<label>Meta Description</label>
										<input type="text" class="form-control"  placeholder="Meta Description" id="metaDescription" name="metaDescription" value="{{ old('metaDescription') }}">
										@if($errors->has('metadescription')) <em class="invalid-feedback"> {{ $errors->first('metadescription') }} </em> @endif
									</div>
									<div>
										<button type="submit" class="btn btn-success">Save</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
            </div>
        </div>
    </div>
    <script src="{{ asset('public/Admin/js/jquery-3.6.0.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/feather.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/jquery.slimscroll.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{ asset('public/Admin/plugins/apexchart/apexcharts.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/script.js')}}"></script>
	<script>
		
		$('#inputImage').change(function(){
			const file = this.files[0];
			
			console.log(file);
			if (file){
			let reader = new FileReader();
			reader.onload = function(event){
				console.log(event.target.result);
				$("#preview").html('<img id="imgPreview" hight="50px" width="50px" src="'+event.target.result+'" alt="pic" />');
				//$('#imgPreview').attr('src', );
			}
			reader.readAsDataURL(file);
			}
		});
		

	</script>
   </body>
</html>

resources/views/admin/submodels/edit.blade.php
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
      <meta name="description" content="POS - Bootstrap Admin Template">
      <meta name="keywords" content="admin, estimates, bootstrap, business, corporate, creative, management, minimal, modern,  html5, responsive">
      <meta name="author" content="Dreamguys - Bootstrap Admin Template">
      <meta name="robots" content="noindex, nofollow">
      <title>Update Sub-Model</title>
      
      <link rel="shortcut icon" type="image/x-icon" href="{{ asset('public/Admin/img/favicon.png')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/bootstrap.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/animate.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/dataTables.bootstrap4.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/plugins/fontawesome/css/fontawesome.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/plugins/fontawesome/css/all.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/style.css')}}">
   </head>
   <body>
      <div id="global-loader">
         <div class="whirly-loader"> </div>
      </div>
      <div class="main-wrapper">
        @extends('layouts.header')
     
        @extends('layouts.sidebar')
        
        <div class="page-wrapper">
            <div class="content container-fluid">
                <div class="page-header">
					<div class="row">
						<div class="col">
							<h3 class="page-title">Update Sub-Model</h3>
							<ul class="breadcrumb">
							    <li class="breadcrumb-item"><a href="{{route('admin.home')}}">{{ trans('global.dashboard') }}</a></li>
							    <li class="breadcrumb-item">
								   @if($brand_sub_model->brand_models_id)
										<a href="{{ route('admin.submodels.show',$brand_sub_model->brand_models_id) }}">Sub-Models</a>
									@else
										<a href="{{ route('admin.brand-type.index') }}">Sub-Models</a>
									@endif
								</li>
							    <li class="breadcrumb-item active">Update Sub-Model</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-12">
						<div class="card">
							<div class="card-body">
								<form action="{{ route('admin.submodels.update', [$brand_sub_model->id]) }}" method="POST" enctype="multipart/form-data">
									{{ csrf_field() }}
									@method('PUT')
									<input type="hidden" name="get_model_id" value="{{ $brand_sub_model->brand_models_id }}">
									<div class="form-group">
										<label>Category<span class="text-danger">*</span></label>
										<select class="form-control @error('brand_type_id') is-invalid @enderror" name="brand_type_id" id="brand_type_id"  >
											<option value="">Select Category</option>
											@foreach($brand_types as $id => $brand_type)
												<option value="{{ $brand_type->id }}" {{ (isset($brand_sub_model) && $brand_sub_model->brand_type_id ? $brand_sub_model->brand_type_id : old('brand_type_id')) == $brand_type->id ? 'selected' : '' }} >{{ $brand_type->name }}</option>
											@endforeach
										</select>
										@if($errors->has('brand_type_id'))
											<em class="invalid-feedback">{{ $errors->first('brand_type_id') }}</em>
										@endif
									</div>
									<div class="form-group">
										<label>Brands<span class="text-danger">*</span></label>
										<select class="form-control @error('brand_id') is-invalid @enderror" name="brand_id" id="brand_id">
											<option value="">Select Brand </option>
											@foreach($brands as $id => $brand)
												<option value="{{ $brand->id }}" {{ (isset($brand_sub_model) && $brand_sub_model->brand_id ? $brand_sub_model->brand_id : old('brand_id')) == $brand->id ? 'selected' : '' }} >{{ $brand->name }}</option>
											@endforeach
										</select>
										@if($errors->has('brand_id'))
											<em class="invalid-feedback">{{ $errors->first('brand_id') }}</em>
										@endif
									</div>
									<div class="form-group">
										<label>Models<span class="text-danger">*</span></label>
										<select class="form-control @error('brand_models_id') is-invalid @enderror" name="brand_models_id" id="brand_models_id"   >
											<option value="">Select Model </option>
											@foreach($models as $id => $model)
												<option value="{{ $model->id }}" {{ (isset($brand_sub_model) && $brand_sub_model->brand_models_id ? $brand_sub_model->brand_models_id : old('brand_models_id')) == $model->id ? 'selected' : '' }} >{{ $model->name }}</option>
											@endforeach
										</select>
										@if($errors->has('brand_models_id'))
											<em class="invalid-feedback">{{ $errors->first('brand_models_id') }}</em>
										@endif
									</div>
									<div class="form-group">
										<label>Sub-model Name<span class="text-danger">*</span></label>
										<input type="text" class="form-control @error('name') is-invalid @enderror" value="{{ old('name', isset($brand_sub_model) ? $brand_sub_model->name : '') }}" placeholder="Sub Model Name" id="name" name="name">
										@if($errors->has('name'))<span class="text-danger">{{ $errors->first('name') }}</span>@endif
									</div>
									<div class="form-group">
										<label>Cut Point</label>
										<input type="number" class="form-control" placeholder="Cut Point" value="{{ old('cut_point', isset($brand_sub_model) ? $brand_sub_model->cut_point : '') }}" id="cut_point" name="cut_point" min="0">
									</div>
									<div class="form-group">
										<label>Status<span class="text-danger">*</span></label>
										<select class="form-control @error('status') is-invalid @enderror" name="status" id="status"  required >
											<option value="0" {{ (isset($brand_sub_model) && $brand_sub_model->status ? $brand_sub_model->status : old('status')) == 0 ? 'selected' : '' }} >Inactive</option>
											<option value="1" {{ (isset($brand_sub_model) && $brand_sub_model->status ? $brand_sub_model->status : old('status')) == 1 ? 'selected' : 'selected' }}>Active</option>
										</select>   
										@if($errors->has('status'))<span class="text-danger">{{ $errors->first('status') }}</span>@endif
									</div>
									<div class="form-group">
										<label>Upload image</label>
										<input type="file" accept="image/*" class="form-control" name="fileUpload" id="inputImage">
									</div>
									<span id="preview">
										@if(isset($brand_sub_model) && $brand_sub_model->image )
											<a href="{{ asset('Admin/images/submodels/'.$brand_sub_model->image)}}" data-lightbox="lightbox-1"> 
												<img src="{{ asset('Admin/images/submodels/'.$brand_sub_model->image)}}" alt="image-preview" width="50"/>
											</a>
										@endif 
									</span>
									<div class="form-group">
										<label>Meta Title</label>
										<input type="text" class="form-control" placeholder="Meta Title" id="metaTitle" name="metaTitle" value="{{ $brand_sub_model->meta_title }}">
										@if($errors->has('metaTitle')) <em class="invalid-feedback"> {{ $errors->first('metaTitle') }} </em> @endif
									</div>
									<div class="form-group">
										<label>Meta Keyword</label>
										<input type="text" class="form-control"  placeholder="Meta Keyword" id="metaKeyword" name="metaKeyword" value="{{ $brand_sub_model->meta_keywords }}">
										@if($errors->has('metaKeyword')) <em class="invalid-feedback"> {{ $errors->first('metaKeyword') }} </em> @endif
									</div>
									<div class="form-group">
										<label>Meta Description</label>
										<input type="text" class="form-control"  placeholder="Meta Description" id="metaDescription" name="metaDescription" value="{{ $brand_sub_model->meta_description }}">
										@if($errors->has('metadescription')) <em class="invalid-feedback"> {{ $errors->first('metadescription') }} </em> @endif
									</div>
									<div>
										<button type="submit" class="btn btn-success">Save</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
            </div>
        </div>
    </div>
    <script src="{{ asset('public/Admin/js/jquery-3.6.0.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/feather.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/jquery.slimscroll.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{ asset('public/Admin/plugins/apexchart/apexcharts.min.js')}}"></script>
   
    <script src="{{ asset('public/Admin/js/script.js')}}"></script>
	<script>
		
		$('#inputImage').change(function(){
			const file = this.files[0];
			
			console.log(file);
			if (file){
			let reader = new FileReader();
			reader.onload = function(event){
				console.log(event.target.result);
				$("#preview").html('<img id="imgPreview" hight="50px" width="50px" src="'+event.target.result+'" alt="pic" />');
				//$('#imgPreview').attr('src', );
			}
			reader.readAsDataURL(file);
			}
		});
		

	</script>
   </body>
</html>