routes/web.php
    Route::put('setting/currency-update', 'Admin\SettingController@updateCurrencySetting')->name('setting.currency-update');

    Route::post('addShopGallery', 'Admin\RetailerController@addShopGallery');
    Route::get('deleteShopGallery', 'Admin\RetailerController@deleteShopGallery');
    Route::get('get-state-list', 'Admin\UsersController@getStateList');
    Route::get('kyc/changeStatus', 'Admin\RetailerController@approveKyc');
    Route::post('kyc/adminChangeStatus', 'Admin\RetailerController@approveKycAdmin');

    Route::resource('recharge-plan', 'Admin\RechargePlanController');
    Route::get('recharge-plan/delete/{id}', 'Admin\RechargePlanController@deleteRechargePlan');
    Route::get('changeStatusRechargePlan', 'Admin\RechargePlanController@changeStatus');
    Route::resource('video', 'Admin\VideoController');
    Route::post('video-order-position', 'Admin\VideoController@videoOrderPosition')->name('videoOrderPosition');
    Route::get('video/delete/{id}', 'Admin\VideoController@deleteVideo');

    Route::resource('video-category', 'Admin\VideoCategoryController');
    Route::post('video-category-order-position', 'Admin\VideoCategoryController@videoCategoryOrderPosition')->name('videoCategoryOrderPosition');
    Route::get('video-category/delete/{id}', 'Admin\VideoCategoryController@deleteVideoCategory');
    Route::get('changeStatusVideoCategory', 'Admin\VideoCategoryController@changeStatus');

    /*PaperSizeController NT09031644*/
    /*Route::resource('/paper-size', 'Admin\PaperSizeController');
    Route::get('/paper-size/delete/{id}', 'Admin\PaperSizeController@deletePaperSize');
    Route::get('/changeStatusPaperSize/', 'Admin\PaperSizeController@changeStatus');
    */

    Route::resource('paper-sizes', 'Admin\PaperSizeController');
    /* ---------create by neha---------*/
    // Route::get('privacypolicy', 'Admin\SettingController@privacypolicy')->name('privacypolicy');

    Route::any('setting/privacypolicy', 'Admin\SettingController@privacypolicy')->name('setting.privacypolicy');
    Route::any('setting/setting_pdf', 'Admin\SettingController@settingpdf')->name('setting.setting_pdf');
    Route::post('setting/settingpdf-update', 'Admin\SettingController@updateSettingPdf')->name('setting.settingpdf-update');
    Route::post('setting/settingpdf-order', 'Admin\SettingController@updateSettingPdfOrder')->name('setting.settingpdf-order');
    Route::post('setting/settingpdf-delete', 'Admin\SettingController@updateSettingPdfDelete')->name('setting.settingpdf-delete');

    Route::put('setting/privacypolicy-update', 'Admin\SettingController@updatePrivacypolicy')->name('setting.privacypolicy-update');
    Route::post('setting/listprivacypolicy', 'Admin\SettingController@listprivacypolicy')->name('setting.listprivacypolicy');


    /* Route::get('customer-recharge-commission', 'Admin\RetailerController@customerRechargeCommission')->name('customer-recharge-commission');*/


    Route::put('fix-commission-update', 'Admin\RetailerController@fixcommissionupdate')->name('fixcommissionupdate');
    Route::put('fix-reward-update', 'Admin\RetailerController@fixrewardupdate')->name('fixrewardupdate');

    Route::get('paper-sizes/delete/{paperSize}', 'Admin\PaperSizeController@deletePaperSize')->name('paper-sizes.delete');
    Route::get('/changeStatusPaperSize/', 'Admin\PaperSizeController@changeStatus');


    Route::resource('generalnotification', 'Admin\GeneralNotificationController');
    Route::post('generalnotification/save', 'Admin\GeneralNotificationController@savenotification')->name('savenotification');
    Route::post('generalnotification/delete/{id}', 'Admin\GeneralNotificationController@delete')->name('deletenotification');
    Route::resource('banner', 'Admin\BannerController');
    Route::post('banner-order-position', 'Admin\BannerController@bannerOrderPosition')->name('bannerOrderPosition');
    Route::get('createBanner/{id}', 'Admin\BannerController@create')->name('createBanner');
    Route::get('bannerdetails/{id}', 'Admin\BannerController@bannerDetails')->name('bannerDetails');
    Route::get('banner/delete/{id}', 'Admin\BannerController@delete');
    Route::get('changeStatusBanner', 'Admin\BannerController@changeStatus');

    Route::resource('bulkcut-plan', 'Admin\BulkCutPlanController');
    Route::get('bulkcut/delete/{id}', 'Admin\BulkCutPlanController@deleteBulkCutPlan');
    Route::get('changeStatusBulkCutPlan', 'Admin\BulkCutPlanController@changeStatus');
    //Divya Route


    /*Member Tree*/
    Route::get('member-tree', 'Admin\RetailerController@showMemberTree')->name('members-tree');
    Route::get('tree-view-retailers/{id}', 'Admin\RetailerController@showMemberTreeDetail')->name('tree-view-retailers');


    Route::get('setting/credit-point', 'Admin\SettingController@creditPoint')->name('setting.credit-point');
    Route::put('setting/credit-point-setting', 'Admin\SettingController@creditPointSetting')->name('setting.credit-point-setting');

    /*commission set*/
    Route::get('setting/commission/{id?}', 'Admin\SettingController@commission')->name('setting.commission');
    Route::put('setting/commission-setting', 'Admin\SettingController@commissionSetting')->name('setting.commission-setting');
    Route::get('setting/commission-setting-report', 'Admin\SettingController@commissionSettingReport')->name('setting.commission-setting-report');

    Route::get('direct-tree', 'Admin\RetailerController@showDirectTree')->name('direct-tree');
    Route::get('direct-users-list', 'Admin\RetailerController@showDirectUserList')->name('direct-users-list');
    Route::get('users-monthly-recharge', 'Admin\RetailerController@usersMonthlyRecharge')->name('users-monthly-recharge');
    Route::get('monthly-recharge-report', 'Admin\RetailerController@monthlyRechargeReport')->name('monthly-recharge-report');
    Route::get('users-credit-purchase', 'Admin\RetailerController@usersCreditPurchase')->name('users-credit-purchase');
    Route::get('credit-purchase-report', 'Admin\RetailerController@creditPurchaseReport')->name('credit-purchase-report');

    Route::get('recharge-commission', 'Admin\RetailerController@rechargeCommission')->name('recharge-commission');
    Route::get('recharge-commission-report', 'Admin\RetailerController@rechargeCommissionReport')->name('recharge-commission-report');
    Route::get('credit-wallet-transaction', 'Admin\RetailerController@creditWalletReport')->name('credit-wallet-transaction');
    Route::get('credit-wallet-report', 'Admin\RetailerController@creditWalletReport')->name('credit-wallet-report');
    Route::get('cash-wallet-transaction', 'Admin\RetailerController@cashWalletTransaction')->name('cash-wallet-transaction');
    Route::get('cash-wallet-report', 'Admin\RetailerController@cashWalletReport')->name('cash-wallet-report');

    Route::get('buyer-list/{id?}', 'Admin\RetailerController@showCustomer')->name('buyer-list');
    Route::get('retailer-customer-list', 'Admin\RetailerController@showCustomerList')->name('retailer-customer-list');
    Route::get('retailer-wise-buyer-list', 'Admin\RetailerController@showRetailerWiseCustomer')->name('retailer-wise-buyer-list');

    Route::get('retailer-credit-balance', 'Admin\RetailerController@showRetailerCreditBalance')->name('retailer-credit-balance');
    Route::get('retailer-credit-balance-report', 'Admin\RetailerController@showRetailerCreditBalanceList')->name('retailer-credit-balance-report');
    Route::get('add-credit-point/{id?}', 'Admin\RetailerController@addCreditPoint')->name('add-credit-point');
    Route::post('add-credit-point-summary', 'Admin\RetailerController@addCreditsSummary')->name('add-credit-point-summary');
    Route::post('add-credit-manual', 'Admin\RetailerController@purchaseCredits')->name('add-credit-manual');

    Route::get('recharge-commission-payout', 'Admin\RechargeCommissionPayout@rechargeCommissionPayout')->name('recharge-commission-payout');
    Route::get('recharge-commission-payout-report', 'Admin\RechargeCommissionPayout@rechargeCommissionPayoutReport')->name('recharge-commission-payout-report');
    Route::put('commission-payout', 'Admin\RechargeCommissionPayout@commissionPayout')->name('commission-payout');

    Route::get('commission-slab-tree-view', 'Admin\RetailerController@commissionSlabTreeViewRetailers')->name('commission-slab-tree-view');

    Route::get('machine-numbers-list', 'Admin\MachineNumbersController@machineNumberDetails')->name('machine-numbers-list');
    Route::get('serial-numbers-list', 'Admin\SerialNumbersController@serialNumberDetails')->name('serial-numbers-list');
    Route::get('paper-sizes-list', 'Admin\PaperSizeController@paperSizeDetails')->name('paper-sizes-list');
    Route::get('user-reactions-list', 'Admin\UserReactionsController@userReactionsDetails')->name('user-reactions-list');
    Route::get('complaint-feedback-list', 'Admin\ComplaintFeedbackController@complaintFeedbackDetails')->name('complaint-feedback-list');
    Route::get('feedback-list', 'Admin\ComplaintFeedbackController@feedbackindex')->name('feedback-list');
    Route::post('complaint_changestatus', 'Admin\ComplaintFeedbackController@change_staus')->name('complaint_changestatus');
    Route::post('changeStausNotification', 'Admin\ComplaintFeedbackController@changeStausNotification')->name('changeStausNotification');

    Route::get('generalnotification-list', 'Admin\GeneralNotificationController@generalNotificationDetails')->name('generalnotification-list');
    Route::post('sendNotification', 'Admin\GeneralNotificationController@notificationSend')->name('notificationSend');
    Route::get('bulkcut-plan-list', 'Admin\BulkCutPlanController@bulkcutPlanDetails')->name('bulkcut-plan-list');
    Route::get('plans-list', 'Admin\PlanController@planDetails')->name('plans-list');

    Route::get('retailer-profile-change-request-list', 'Admin\RetailerController@paperSizeDetails')->name('retailer-profile-change-request-list');

app/Models/GeneralNotification.php
<?php

namespace App\Models;
use App\User;
use Illuminate\Database\Eloquent\Model;
use DB;
class GeneralNotification extends Model
{
    //protected $fillable = ['title','image','message','user_id'];

    public function users(){
       return $this->belongsTo(User::class,'user_id','id');
   }
    
}

resources/views/admin/generalnotifications/generalNotification-list.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
      <meta name="description" content="POS - Bootstrap Admin Template">
      <meta name="keywords" content="admin, estimates, bootstrap, business, corporate, creative, management, minimal, modern,  html5, responsive">
      <meta name="author" content="Dreamguys - Bootstrap Admin Template">
      <meta name="robots" content="noindex, nofollow">
      <title>General Notification List</title>
      
      <link rel="shortcut icon" type="image/x-icon" href="{{ asset('public/Admin/img/favicon.png')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/bootstrap.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/animate.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/dataTables.bootstrap4.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/plugins/fontawesome/css/fontawesome.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/plugins/fontawesome/css/all.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/style.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/plugins/select2/css/select2.min.css')}}">
      <meta name="csrf-token" content="{{ csrf_token() }}">
      <link rel="stylesheet" href="{{ asset('public/Admin/tabulator/bootstrap/tabulator_bootstrap4.css')}}">
  </head>
  <body>
    <div class="main-wrapper">
		@extends('layouts.header')
		@extends('layouts.sidebar')
		<div class="page-wrapper">
			<div class="content container-fluid">
				<div class="page-header">
					<div class="row">
						<div class="col">
							<h3 class="page-title">General Notification List</h3>
							<ul class="breadcrumb">
								<li class="breadcrumb-item"><a href="{{ route('admin.home') }}">{{ trans('global.dashboard') }}</a></li>
								<li class="breadcrumb-item active">General Notification List</li>
							</ul>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-sm-12">
						<div class="card">
							<div class="card-header row">
								<div class="col-lg-6">
									<h4 class="card-title">General Notification List</h4>
								</div>
								<div class="col-lg-6">
									<a href="{{ route('admin.generalnotification.create') }}" class="btn btn-success" style="float: right;">+ {{ trans('global.add') }} {{ trans('cruds.generalnotifications.title_singular') }}</a>
								</div>
							</div>
							<div class="card-body">
								<div class="table-responsive">
									<button class="btn btn-outline-info waves-effect" id="download-csv">Download CSV</button> <p><br/></p>
									<div id="data-table-general-notification"></div>
								
									<div class="modal fade" id="notificationModel"  role="dialog" >
										<div class="modal-dialog modal-dialog-centered" role="document">
											<div class="modal-content">
												<div class="modal-header">
													<h5 class="modal-title">Modal title</h5>
													<button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"><span aria-hidden="true">X</span></button>
												</div>
												<form id="formOfNotification" action="{{ route('admin.notificationSend') }}" method="POST" >
													<div class="modal-body">
														<input type="hidden" name="id" id="id" value="">
														<input type="hidden" name="_token" value="{{ csrf_token() }}">
														
														<div class="form-group row">
															<div class="col-sm-4">
																<label for="comment">Notification</label>
															</div>
															<div class="col-sm-8">
																<input type="checkbox" id="notfication" name="notfication" onchange="
																if ($(this).prop('checked')==true){
																	$('.popup').attr('style','display:block')
																}else{
																	$('.popup').attr('style','display:none');
																}">
															</div>
															<div class="col-sm-4 popup" style="display:none">
																<label for="comment">Send as a popup</label>
															</div>
															<div class="col-sm-8 popup" style="display:none">
																<input type="checkbox" id="sendaspopup" name="sendaspopup">
															</div>
														</div>
														<div class="modal-footer">
															<button type="submit" class="btn btn-primary">Save changes</button>
															<button type="button" data-bs-dismiss="modal" class="btn btn-secondary">Close</button>
														</div>
													</div>
												</form>
											</div>
										</div>
									</div>
								
								</div>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
    </div>
    <script src="{{ asset('public/Admin/js/jquery-3.6.0.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/feather.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/jquery.slimscroll.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/script.js')}}"></script>
    <script type="text/javascript" language="javascript" src='https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js' defer></script>
    <script type="text/javascript" language="javascript" src='https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js' defer></script>
    <script type="text/javascript" language="javascript" src='https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js' defer></script>
    <script type="text/javascript" language="javascript" src='https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js' defer></script> 
    <script src="{{ asset('public/Admin/tabulator/tabulator.min.js') }}"></script>
    <script src="{{ asset('public/Admin/tabulator/jspdf.min.js') }}"></script>
    <script src="{{ asset('public/Admin/tabulator/xlsx.full.min.js') }}"></script>
    <script src="{{ asset('public/Admin/tabulator/jspdf.plugin.autotable.js') }}"></script>
    <script type="text/javascript">
      var tabledata = <?php echo json_encode($generalnotifications); ?>;
      console.log(tabledata);
      function customFilter(data){
          return data.car && data.rating < 3;
      }

      function updateFilter(){
        var filter = $("#filter-field").val() == "function" ? customFilter : $("#filter-field").val();
        if($("#filter-field").val() == "function" ){
          $("#filter-type").prop("disabled", true);
          $("#filter-value").prop("disabled", true);
        }else{
          $("#filter-type").prop("disabled", false);
          $("#filter-value").prop("disabled", false);
        }
        table.setFilter(filter, $("#filter-type").val(), $("#filter-value").val());
      }

      //Update filters on value change
      $("#filter-field, #filter-type").change(updateFilter);
      $("#filter-value").keyup(updateFilter);
      

      var table = new Tabulator("#data-table-general-notification", {
        data:tabledata,           //load row data from array
        layout:"fitColumns",      //fit columns to width of table
        responsiveLayout:"collapse",  //hide columns that dont fit on the table
        tooltips:true,            //show tool tips on cells
        addRowPos:"top",          //when adding a new row, add it to the top of the table
        history:true,             //allow undo and redo actions on the table
        pagination:"local",       //paginate the data
        paginationSize:10,         //allow 7 rows per page of data
        movableColumns:true,      //allow column order to be changed
        resizableRows:true,       //allow row order to be changed
        initialSort:[             //set the initial sort order of the data
            {column:"id", dir:"desc"},
        ],
        columns: [
          {title:"Title", field:"title", editor:"label",headerFilter:"input",headerFilterPlaceholder:"Title"},
          {title:"Image", field:"image", 
            formatter:function(cell, formatterParams, onRendered){
              if(cell.getValue() != ""){
                var url = "{{ asset('Admin/images/notifications/:id')}}";
                url = url.replace(':id', cell.getValue());
                return '<img src="'+url+'" style="width:60px;height:60px; margin: 5px 5px 5px 0;">';
              }else{
                return "";
              }
            }
          },
          {title:"Retailer", field:"user_name", 
            formatter:function(cell, formatterParams, onRendered){
            	var arr = cell.getValue();
							var data = arr.split("_");
              if(data[1] != ''){
                var show_url = "{{ route('admin.retailers.show',':id') }}";
                show_url = show_url.replace(':id', data[1]);
                
                return '<a href="#">'+data[0]+'</a>';
              }else{
                return "All";
              }
            }
          },
		      {title:"Action", field:"id", 
            formatter:function(cell, formatterParams, onRendered){
              var view_url = '{{ route("admin.generalnotification.show", ":id")}}';
              view_url = view_url.replace(':id', cell.getValue());

              var edit_url = '{{ route("admin.generalnotification.edit", ":id")}}';
              edit_url = edit_url.replace(':id', cell.getValue());

              var delete_url = '{{ route("admin.generalnotification.destroy",":id")}}';
              delete_url = delete_url.replace(':id', cell.getValue());
			  			var msg = "Are you sure you want to delete this Notification?";
							var token = '{{ csrf_token() }}';

              var link = '<a  href="'+view_url+'" class="btn btn-primary text-white"><i class="fa fa-eye "></i></a><a  href="'+edit_url+'" class="btn btn-success text-white"><i class="fa fa-edit "></i></a><form action="'+delete_url+'" method="POST" onclick="$(\'#is_delete\').val(1)" onsubmit="return confirm(\''+msg+'\');" style="display: inline-block;"><input type="hidden" name="_method" value="DELETE"><input type="hidden" name="_token" value="'+token+'"><button type="submit" class="btn btn-danger danger-icon-notika btn-reco-mg btn-button-mg waves-effect"> <i class="fa fa-trash"></i></button></form><button class="btn btn-primary  text-white sa-warning waves-effect" data-bs-toggle="modal" data-bs-target="#notificationModel" onclick="popupmodel(this)" data-id="'+cell.getValue()+'"><i class="fa fa-times-circle"></i></button>';
                  return link; 
            },
          }
        ],
      });
	  
	  function popupmodel(current){
		  var action_url = $(current).data('url');
		  $("#formOfNotification").attr("action",action_url);
		  $("#formOfNotification").find("#id").val($(current).data("id"));
	  }

      //trigger download of data.xlsx file
      document.getElementById("download-csv").addEventListener("click", function(){
          table.download("csv", "data.csv");
      });
    </script>
  </body>
</html>

resources/views/admin/generalnotifications/index.blade.php
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
      <meta name="description" content="POS - Bootstrap Admin Template">
      <meta name="keywords" content="admin, estimates, bootstrap, business, corporate, creative, management, minimal, modern,  html5, responsive">
      <meta name="author" content="Dreamguys - Bootstrap Admin Template">
      <meta name="robots" content="noindex, nofollow">
      <title>{{ trans('cruds.generalnotifications.title_singular') }} {{ trans('global.list') }}</title>
      
      <link rel="shortcut icon" type="image/x-icon" href="{{ asset('public/Admin/img/favicon.png')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/bootstrap.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/animate.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/dataTables.bootstrap4.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/plugins/fontawesome/css/fontawesome.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/plugins/fontawesome/css/all.min.css')}}">
      <link rel="stylesheet" href="{{ asset('public/Admin/css/style.css')}}">
   </head>
   <body>
      <div id="global-loader">
         <div class="whirly-loader"> </div>
      </div>
      <div class="main-wrapper">
        @extends('layouts.header')
     
        @extends('layouts.sidebar')
        
        <div class="page-wrapper">
            <div class="content container-fluid">
               <div class="page-header">
                  <div class="row">
                     <div class="col">
                        <h3 class="page-title">{{ trans('cruds.generalnotifications.title_singular') }} {{ trans('global.list') }}</h3>
                        <ul class="breadcrumb">
                           <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">{{ trans('global.dashboard') }}</a></li>
                           <li class="breadcrumb-item active">{{ trans('cruds.generalnotifications.title_singular') }} {{ trans('global.list') }}</li>
                        </ul>
                     </div>
                  </div>
               </div>
               <div class="row">
                  <div class="col-sm-12">
                     <div class="card">
                        <div class="card-header row">
                            <div class="col-lg-6"><h4 class="card-title">{{ trans('cruds.generalnotifications.title_singular') }} {{ trans('global.list') }}</h4></div>
                            <div class="col-lg-6"><a href="{{ route('admin.generalnotification.create') }}" class="btn btn-success" style="float: right;">+ {{ trans('global.add') }} {{ trans('cruds.generalnotifications.title_singular') }}</a></div>
                        </div>
                        <div class="card-body">
                           <div class="table-responsive">
                              <table class="table  datanew ">
                                 <thead>
                                    <tr>
                                       <th>Title</th>
                                       <th>Image</th>
                                       <th>Retailer</th>
                                       <th>Action</th>
                                    </tr>
                                 </thead>
                                 <tbody>
                                    @foreach($generalnotifications as $key => $generalnotification)
                                    <tr>
                                       <td>{{ $generalnotification->title ?? '' }}</td>
                                       <td>@if($generalnotification->image)
                                          @php
                                          $myArray = json_decode($generalnotification->image, True); 
                                          @endphp
                                          @if( $myArray === NULL )
                                          <img src="{{ asset('Admin/images/notifications/'.$generalnotification->image) }}" style="width:60px;height:60px; margin: 5px 5px 5px 0;">
                                          @else
                                          @foreach($myArray as $key => $value)
                                            <img src="{{ asset('Admin/images/notifications/'.$value) }}" style="width:60px;height:60px; margin: 5px 5px 5px 0;">
                                          @endforeach
                                          @endif
                                          @endif
                                       </td>
                                       <td>
                                          @if(!empty($generalnotification->user_id))
                                                   <a href="{{ route('admin.retailers.show', $generalnotification->users->id ?? 0 ) }}"> 
                                                      {{ $generalnotification->users->name ?? '' }}
                                                   </a>
                                                  @else
                                                   All
                                          @endif
                                       </td>
                                       <td>
                                          <a  href="{{ route('admin.generalnotification.show', $generalnotification->id)}}" class="btn btn-primary text-white"><i class="fa fa-eye "></i></a>

                                          <a  href="{{ route('admin.generalnotification.edit', $generalnotification->id)}}" class="btn btn-success text-white"><i class="fa fa-edit "></i></a>

                                          <a  href="{{ url('admin/generalnotification/delete', $generalnotification->id) }}" class="btn btn-danger text-white"><i class="fa fa-trash "></i></a>
                                             
                                    </tr>
                                    @endforeach
                                 </tbody>
                              </table>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
    <script src="{{ asset('public/Admin/js/jquery-3.6.0.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/feather.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/jquery.slimscroll.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{ asset('public/Admin/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{ asset('public/Admin/plugins/apexchart/apexcharts.min.js')}}"></script>
    <script src="{{ asset('public/Admin/plugins/apexchart/chart-data.js')}}"></script>
    <script src="{{ asset('public/Admin/js/script.js')}}"></script>
   </body>
</html>